---
name: cxy_cassandra
director_uuid: f21dba61-68fc-4d15-b0a8-462fd82b651f
release:
  name: cxy_cassandra
  version: latest
compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 1
  max_errors: 1

networks:
- name: default
  subnets:

  - range: 10.244.0.0/24
    reserved:
      - 10.244.0.1
    static:
      - 10.244.0.2-10.244.0.240
    cloud_properties:
      name: random

resource_pools:
- name: warden
  network: default
  size: 2
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties: {}
jobs:
- name: cassandra
  template: cassandra
  instances: 2
  resource_pool: warden 
  networks:
  - name: default
    static_ips:
    - 10.244.0.54
    - 10.244.0.58
properties:
  cassandra:
    cluster_name: WizardDemoCluster 
